apiVersion: v1
kind: ServiceAccount
metadata:
  name: grype-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grype-db
  labels:
    app: grype-db
    tier: web
spec:
  serviceName: grype-db
  replicas: 1
  selector:
    matchLabels:
      app: grype-db
      tier: web
  template:
    metadata:
      labels:
        app: grype-db
        tier: web
    spec:
      containers:
      - name: grype-db
        image: bingbangboo/grype-listing.json-rewriter
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "0.1"
            memory: "200Mi"
        env:
          - name: BASE_URL
            value: /
          - name: BIND_SCHEME
            value: "http"
          - name: PUBLIC_SCHEME
            value: "http"
          - name: PUBLIC_HOSTNAME
            value: "grype-db"
          - name: BIND_HOSTNAME
            value: "0.0.0.0"
          - name: BIND_PORT
            value: "8080"
          - name: PUBLIC_PORT
            value: "80"
          - name: DB_URL_COMPONENT
            value: "databases"
          - name: UPSTREAM_LISTING_URL
            value: "https://toolbox-data.anchore.io/grype/databases/listing.json"
          - name: OUTPUT_DIR
            value: "/databases"
          - name: MINIMAL
            value: "true"
          - name: VERBOSE
            value: "true"
        volumeMounts:
        - name: databases
          mountPath: /databases
          readOnly: false
      serviceAccount: grype-db
      automountServiceAccountToken: false
  volumeClaimTemplates:
  - metadata:
      name: databases
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grype-db
  labels:
    app: grype-db
    tier: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: web
  selector:
    app: grype-db
    tier: web
